# Generated by Django 3.2.4 on 2021-07-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0005_alter_website_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
